### ISSUE TITLE
not threadsafe? in puma every so many requests, empty gon data

### ISSUE THREAD

**Issue by wogg** [gazay/gon#100]
Looking at the code and it's use of class methods and data, it seems pretty clear that this gem isn't safe for use in a threaded Rails environment?

I'm guessing that's what all the checks for "wrong request" are about?

Anyway, in our environment it seemed to work fine under unicorn (not threaded), but under puma, randomly the include_gon render would just have empty data, and the only thing I could find to explain that was your check for request.object_id != Gon::Request.id and it's side effects in "include_gon" in helpers.rb

**Comment by PericlesTheo** [comment]
I just received this error as well `ActionView::Template::Error`can't add a new key into hash during iteration`.

I'm using Rails 4.2 with Puma, Ruby 2.2 and gon 6.0.1
