### ISSUE TITLE
Incompatible character encodings ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by decasia** [gazay/gon#120]
I'm seeing mysterious template errors that seem to stem from the `include_gon` directive. I'm running Rails 3.2.16 and Gon 5.0.4. The error trace looks like this:
 
```ruby
ActionView::Template::Error (incompatible character encodings: ASCII-8BIT and UTF-8):
    10:     - if Rails.env.production?
    11:       = stylesheet_link_tag "https://server.uchicago.edu/shared/stylesheets/application.css"
    12:     = javascript_include_tag 'application'
    13:     = include_gon
    14:     = javascript_include_tag @controller_js if @controller_js.present?
    15:     /[if lt IE 10]
    16:       = stylesheet_link_tag 'ie8'
  app/views/layouts/application.html.haml:13:in `_app_views_layouts_application_html_haml__3764659976690600365_39838620'
  app/controllers/faculty_reports_controller.rb:124:in `show'
```

Here's a sample of what gon is spitting out on this page (when the mysterious encoding error doesn't occur):

```javascript
//<!CDATA[

window.gon={};gon.current_tab=10;gon.department_list=[{"label":"Art History","category":"Humanities"}, [...more entries like this],];gon.directory_url="https://url_to_our_directory_service/directory/search.js"; 

//]]>
```

To make matters worse, the exception only happens intermittently, on a particular user's client. As far as I know, the data I'm passing to gon is standard Ruby text variables -- should I be deliberately encoding it as UTF8? Is there some other debugging procedure I could employ to track down the exact source of the problem?

**Comment by takiy33** [comment]
I will close this issue because it is inactive for several years.

**Comment by manfe** [comment]
Guys, just to let you know what I am experiencing about it.

Searching about the same problem I came to this issue: basically what happens for me. When I set a string with non-ascii characters, in my case a string with `ã` character was causing this error. I still couldn't find a way to fix it.

I just can tell that when a variable is set the variable is considered binary and when rails/ruby try to concatenate raise this error.

If you guys found something please post here.
