### ISSUE TITLE
gon.watch not working in Rails 4. Gives undefined method for nilClass

### ISSUE THREAD

**Issue by tmrudul** [gazay/gon#133]
I'm able to use gon.varaible_name in my controllers but when I do gon.watch.variable_name it gives 

```
undefined method `variable_name=' for nil:NilClass
```

I have initialized gon as

```
<%= include_gon(:init => true) %>

```

**Comment by takiy33** [comment]
Could you try to use `<%= Gon::Base.render_data %>` instead of `<%= include_gon(:init => true) %>`?

**Comment by takiy33** [comment]
I will close issue because it is inactive.
