### ISSUE TITLE
Why doesn't gon cover redirects?

### ISSUE THREAD

**Issue by andreasklinger** [gazay/gon#137]
It seems a bit odd that gon doesn't cover redirects at all.

I understand that after a redirect state is lost.

But in many cases gon is used a way like

```
if @foo.save
  gon.push(...)
  redirect_to etc_path
else
   #… 
end
```

Wouldnt it be interesting to offer a way to persist those variables between requests?

Basically patching `redirect_to` to reuse `flash` to store the variables between requests.
If it's a concern to store all there could be a special flag or method to mark the variables that should be remembered.

**Comment by Rendez** [comment]
@andreasklinger great solution for Rails. This should be added to the docs or F.A.Q somewhere.
