### ISSUE TITLE
Fragment caching of gon 

### ISSUE THREAD

**Issue by justin808** [gazay/gon#160]
Is it possible to place this statement inside of the cache block:

```
- cache(key) do
- call_code_to_set_up_gon
= include_gon(camel_case: false)
- end
```

And then to setup the gon variables inside the cache block.

Thanks.

**Comment by takiy33** [comment]
Thank you for sending Issue.

> Is it possible to place this statement inside of the cache block:

I do not know gon works intently because I think gon is not supposed to this situation.
