### ISSUE TITLE
Cannot use url helpers with jbuilder

### ISSUE THREAD

**Issue by JohnColvin** [gazay/gon#161]
I cannot get gon to render jbuilder templates with a url_helper. The jbuilder code seems to be including ActionView::Helpers, though. Any advice to fix this issue? This is rails 3.2 with gon 5.2.0.

Calling the url_helper on `controller.view_context` works around the issue, but I'd rather not have to do that in the templates.

Thanks!

**Comment by jarinudom** [comment]
I'm having the same issue on Rails 4.2.0. For example, I have to do this:

```ruby
# company.json.jbuilder
json.extract! company, :id, :ticker, :name, :last_close, :market_cap
json.url controller.view_context.company_url(company)
```

**Comment by gazay** [comment]
Should be solved by PR above. New version soon, for now please use master
