### ISSUE TITLE
RuntimeError is raised when I use gon.name

### ISSUE THREAD

**Issue by takiy33** [gazay/gon#176]
*RuntimeError (You can't use Gon public methods for storing data)* is raised when I use gon.name.

## Environment

Environment|Version
---|----
Ruby|ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Rails|4.2.1
gon|5.2.3

**Comment by gazay** [comment]
Hello, yes it is expected behavior as gon using metaprogramming to set variables as methods of gon class. So it doesn't allow to use public methods as variable names because it can break functionality of whole gem. Please try different name, like `user_name`

**Comment by gazay** [comment]
https://github.com/gazay/gon/blob/master/lib/gon.rb#L39 you can find this functionality here

**Comment by takiy33** [comment]
I understand. Thank you for why gon.name is not avaible.

**Comment by clreddy21** [comment]
The issue public method error can be fixed if you can downgrade the gon to 5.2.0 from 5.2.3. It worked for me.
