### ISSUE TITLE
Gon attributes are not being cleared between rspec controller tests

### ISSUE THREAD

**Issue by tbrammar** [gazay/gon#179]
In an Rspec controller test:

````
context 'value is set' do
  # some condition required to make gon variable available 
  
  it 'should return value' do
    get :new
    expect(controller.gon.foo).to eq 'bar'
  end
end

it 'should not return value' do
  # some condition required to make gon variable available 

  it 'should return value' do
    get :new
    expect(controller.gon.foo).to eq nil
  end
end
````

The first test passes and the second test passes  *as long as it's run sequentially before the first*. If it gets run after the first test it fails. 

If I ask it to output value before running the test:

````
  it 'should return value' do
    puts controller.gon.foo
    get :new
    expect(controller.gon.foo).to eq nil
  end
````

...it outputs the value from the previous test.

Seems like the values are not being cleared between tests.

[Rails 4.2.1,  Rspec 3.2.0, Gon 5.2.3]

**Comment by takiy33** [comment]
Thank you for opening issue.

## Reason

Gon gem uses [RequestStore](https://github.com/steveklabnik/request_store) gem for storing data.
RequestStore uses Rack middleware to clear data.(value is not held in another request)
Controller spec does not use Rack middleware. As a result, data is not cleared in another request.

## Solution

Please clear data in after hook like below.

```ruby
after do
  Gon.clear
end
```
