### ISSUE TITLE
Getting error in ruby 1.8.7 after installing gem

### ISSUE THREAD

**Issue by aka001** [gazay/gon#184]
After including "gem "gon" " in Gemfile and running "bundle install", I am getting this error while running rails server (rails s)
http://pastebin.com/Dxtxcqbv
I am using "ruby 1.8.7". Is "gon" compatible with this version ?

**Comment by gazay** [comment]
Hello! The last version with support for 1.8.7 was 4.0.3 https://github.com/gazay/gon/blob/master/CHANGELOG.md#410. I'm suggest to update Ruby if you can as 1.8.7 long time dead and not supported by Ruby team.

**Comment by aka001** [comment]
@gazay Okay got it. Thanks.
