### ISSUE TITLE
Gon defined only when user directly access page, not defined when user is linked to a page

### ISSUE THREAD

**Issue by jmzbond** [gazay/gon#187]
Really struggling with this one... If I visit the page where I need to have gon variables defined, i.e., if I navigate to www.myhost.com/users/signup, everything works fine. But most users will get to that page via a redirect from the home page (they click on a link). Given that gon is defined in the backend in the action that serves up the users/signup template (and indeed, I can confirm via a `puts` statement that the gon is always successfully defined in the action), why is it not available in the rendered template? And only (again) when the user is linked to the page?

    # Staticpages/home
    def home
    end

    # home.html.erb (/)
    <%= link_to "Sign up", new_user_registration_path %>

    # Where the route above links to Users::Registrations/new
    def new
        gon.zipcode_list = zipcode_list
        puts gon.zipcode_list #note this push always returns the right value, so in the server side, gon is working fine
    end

    # new.html.erb (/users/signup)
    <script>
        alert(gon.zipcode_list)
        // the alert above fires ONLY when I navigate to /users/signup. When I click on the link in the homepage, it does NOT fire, and there's a console error that gon is undefined
    </script>

**Comment by Bariseray** [comment]
Try putting <%= Gon::Base.render_data %> in to the body of your application.html.erb instead of the head section. Believe this is an issue with turbolinks

**Comment by pablougas** [comment]
I am running into a similar issue...

**Comment by pablougas** [comment]
A little frustrating but all I did was add <%= include_gon %> on the top of that specific view and it worked. No idea why but I'll take it.

**Comment by gazay** [comment]
As I see, the reason of this behavior is that you use something like turbolinks or similar instrument, which re-render only part of the view and don't touch gon area
