### ISSUE TITLE
Progressively populate array referenced by gon in the background

### ISSUE THREAD

**Issue by dekhaus** [gazay/gon#192]
Hi All

  I'd like to use gon in what I'm concerned may be incorrect manner - so I thought I'd post here first with a few questions before investing too much time.
  
  I have a large collection of items (~10,000) that is somewhat static - let's call this collection 'all_assets'.  My backend is a Rails4 application and the front-end is an AngularJS app.  'all_assets' is used on many of the pages of my Angular app.
  
  One of the pages on my site has an angular-datatable grid and I've written this page to progressive load all the Assets.  It takes approximately 10 seconds for all the data to download.
  
  As an experiment - I added the following to my Rails application controller ...
  
    gon.all_assets = Asset.all
    
  and I then updated the aforementioned grid page to reference gon.all_assets.  Instead of taking approximately 10 seconds for the grid to load all the data - the grid appears with all its data in about 1 second.
  
  I noticed that loading the first page of the site takes an additional 1-2 seconds longer than it did -  obviously because of the overhead of downloading the Asset data (Asset.all).
  
  I'm very impressed with gon and I thought with a few tweaks - it would work perfectly for me.
  
  My idea is to create a background job in my Rails app and progressively populate gon.all_assets ...
  
    - in application_controller.rb
    
        before_filter :progressively_load_assets
        ...
        
        def progressively_load_assets
          gon.all_assets = []
          gon.number_of_assets_per_page = 500
          gon.total_number_of_assets = Asset.count
          LoadAllAssetsWorker.perform_async
        end
        
    - in a Sidekiq 'worked' LoadAllAssetsWorker.rb ...
    
        def perform
          current_page = ... (perform some calculation to determine 'current_page' )
          gon.all_assets << Asset.retrieve_page_from_db(current_page)
        end
  
  There are two critical questions I have ...
  
  1) How can I access the 'gon' object in the Sidekiq background 'worker' ?  (I'm sure its a bad idea to pass it in as parameter - aka serialization issues)
  
  2) Is what I'm proposing to do above 'thread safe' ?
  
  I'm trying to progressively add Assets to gon.all_assets so as to minimize the time it takes for my Rails application to respond to a request.  If there's a better way to do this - please let me know how.  
  
  I am aware of gon.watch - but I don't see how that could be used to progressively load an array referenced by gon. If there is a way it can be used - please tell me how.
  
Thanks
Dave

**Comment by gazay** [comment]
Hello Dave!
1. You can't access gon object from anywhere except controllers and views as it is just a helper. You can access Gon::Global instead and in js it will be available from gon.global namespace.

Let I tell you how gon works and maybe you'll find solution for your task faster (as I maybe don't understand partially what you want to achieve by using sidekiq for different pages):
1. You have different routes which point to different controller actions. Let say we have root (Home#index) and show (Home#show).
2. In index you have to show all the data from your database in JS, so in action you write `gon.assets = Asset.all`, in show you need only scoped data: `gon.assets = Asset.where(page: params[:id])`.
2'. In view layout you have `include_gon(your options)`
3. In your browser you make root request.
  3a. Rails receive this request and goes to `index` action of Home controller. There is our line `gon.assets = Asset.all`.
  3b. This `gon` – is a controller helper, which checks controller's environment: gon stores inside its storage request identifier. Gon needs it to work only with data, which related just to current request. For example on next request gon still have data from first request, but as identifiers of requests doesn't match – it will erase old data.
  3c. After gon checked and renewed request uuid – it can store data, so it does.
  3d. Rails finishes logic in controller's action and start rendering.
4. When rails start render it meet line `include_gon(your options)` in your layout and it is also a helper (but this time view helper, so it is accessible from views) as `gon` in controller.
  4a. This helper also have info which request we working with (it's uuid), and it checks - is there a data it should prepare for this request
  4b. It gather all data for this request and transform it to javascript tag with json data you can access from your javascript.
  4c. No matter what request right now – it checks is there global data (from Gon::Global)? If it is - it will render it anyway in namespace `gon.global`.

Is this helpful information? If you want more explanation or more help with your task – please describe why you want to use sidekiq? If this is a static data and should be available on many pages – you can just render it once in js.erb file and include it in custom layout for those pages. It will be faster than using gon.

**Comment by dekhaus** [comment]
Hi

Thanks for the informative response - I really appreciate the time you took to respond.

I've re-evaluated my requirements and solved my issue without using gon - but rather, by using periodic ajax calls.

Thanks Again
Dave
