### ISSUE TITLE
Cannot get updated variable in JS gon

### ISSUE THREAD

**Issue by koxta19** [gazay/gon#196]
Hi, I already find people with the same issue, but not a solution to my problem.
I used gon.watch.var to send variable to JS but it assumes only the value given at the controller loading. When I try to update the var inside a method for a clicked button, the value changes inside controller but gon.watch shows only the first value.
Does anyone know how to solve this? Thanks.

**Comment by ikneg** [comment]
+1

**Comment by kfarst** [comment]
@koxta19 did you make sure to pass it an interval to check it and a function to call when the Ruby variable is updated?

` gon.watch('foo', { interval: 1000 }, updateView);`

Then in the `updateView` function:

```
function updateView (newVal) {
  $('name_of_css_selector').text(newVal);
}
```

**Comment by takiy33** [comment]
@koxta19 Thank you for replying issue.

**Comment by takiy33** [comment]
I wil close this issue because it is inactive.
