### ISSUE TITLE
Does not work with after_action callback

### ISSUE THREAD

**Issue by ozgun** [gazay/gon#201]
Hi,

I call `gon.push` method from inside and `after_action` method such as:

```ruby
after_action :set_js_variables

protected

def set_js_variables
  gon.push(a: 1)
end
```

However, when I check HTML source, I  see:

```
<script>
//<![CDATA[
window.gon={};
//]]>
</script>
```

But, if I use `before_action` instead of `after_action`, it works as expected.

Thanks.

**Comment by gazay** [comment]
After action callback runs after rendering phase of action. Gon renders its data during rendering phase. So it's expected behavior. Thank you for issue!
