### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by lipanski** [gazay/gon#203]
hi

could you release a new version please?
there appears to be a small versioning issue https://github.com/gazay/gon/releases - 6.0.0 came after 6.0.1.

**Comment by takiy33** [comment]
Thank you for sending Issue.
I think that tag object's date is causing.
[Releases](https://github.com/gazay/gon/releases) is sorted by tag object's date.
Please see below links.

* https://rubygems.org/gems/gon
* https://help.github.com/articles/about-releases/
