### ISSUE TITLE
Warning when upgrading to rails 5 rc

### ISSUE THREAD

**Issue by tibastral** [gazay/gon#208]
At the line of my gon assignation :

DEPRECATION WARNING: env is deprecated and will be removed from Rails 5.1 (called from block in <class:ApplicationController> at /Users/thibaut/goinfre/rushout/app/controllers/application_controller.rb:12)

    gon.places_categories = 'test'

**Comment by takiy33** [comment]
Thank you for issue.
This warning is fixed #202.
