### ISSUE TITLE
[Rails 4] Uncaught ReferenceError: gon is not defined 

### ISSUE THREAD

**Issue by ironsand** [gazay/gon#217]
Hi,

I got a `uncaught reference error` in Rails 4 environments.

To solve the error, I need to replace `<%= include_gon %>` to `<%= include_gon(:init => true) %>`.
http://stackoverflow.com/questions/24541445/rails-gon-is-not-defined-error

I think it's better to write this information in `README.md`. If it's necessary I'll send a pull request for it.

Thanks

**Comment by gazay** [comment]
Hello! Thank you for issue. This option not really for that - it just renders `window.gon={}` on each request, even if there are no gon variables set. How it fixes `uncaught reference error` I don't really understand, but if you can create small app which shows this problem – I can debug and fix it properly

**Comment by ironsand** [comment]
Thanks for quick reply.

Sorry, it's hard for me to create a project that reproduces the behavior. I just uploaded my project here. https://github.com/ironsand/tangocho

I think it's small enough.

**Comment by gazay** [comment]
Thank you! Is that error happened in development mode or in production too?

**Comment by gazay** [comment]
I've started your project without `init: true` option and on root route (`localhost:3000/`) exception didn't happened – where it was?

**Comment by ironsand** [comment]
The error occurs in development mode at root path.
Maybe it's only in my environments.

I'm using macOS Sierra 10.12.1, Chrome 54.0.2840.98(64-bit).
I open the page by Chrome secret mode to avoid being affected Add-ons.

I'll try it another environments later.

**Comment by ironsand** [comment]
Sorry, I was busy and couldn't take time for check this issue. After updating the project to rails 5 there is no error anymore. So I close this issue. Thanks.
