### ISSUE TITLE
You can't use Gon public methods for storing data

### ISSUE THREAD

**Issue by raisty** [gazay/gon#226]
I have following error on gon v. 5.2.3
`You can't use Gon public methods for storing data`

Problematic code:
`gon.current_user = { sn: current_user.sn }`

**Comment by bhaveshf-cuelogic** [comment]
@raisty : You must be having some public method named `current_user` somewhere in your code. Are you using devise gem ?

**Comment by raisty** [comment]
You are absolutely true. The problem is with public method named current_user
