### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by franzliedke** [gazay/gon#233]
We're currently using the latest master, as there hasn't been a release in a long time. Any chance you could release the current master as version 6.2.0? :smile:

**Comment by gazay** [comment]
I've released 6.2.0 but it seems something changed and specs are not green now. I'll look why later. Thank you :)

**Comment by franzliedke** [comment]
Judging by the failing tests, [this commit](https://github.com/ccocchi/rabl-rails/commit/12a3f0f72dca4ba2112398b26b80912462ab40c6) in rabl-rails seems to be the problem.
