### ISSUE TITLE
The right way to test conents from gon with jasmine?

### ISSUE THREAD

**Issue by romanblick** [gazay/gon#40]
Hi,

we use rspec to generate fixtures:
https://gist.github.com/969252/dd89e73e6e1a6c233afe71896e79bcd923750521

And finally, we use jasmine to load these fixtures and test our coffee/javascript logic. I think this way is not very common. Is there another way to test the frontend aplicationcode with jasmine, when it contains contents from gon in its header?

**Comment by lauriegriffiths** [comment]
Just a note for anyone encountering this issue. 
We had a similar approach of saving fixtures during integration tests, then not being able to read the gon data during jasmine specs. 
The solution was to also parse and save the gon data from the dom as a json file during the integration tests, then to load this data as a fixture.

**Comment by lauriegriffiths** [comment]
pairing on @lauriegriffiths machine whilst he's not present, so just a note that it was @markburns that said this.
