### ISSUE TITLE
undefined local variable or method `include_gon'

### ISSUE THREAD

**Issue by sergio-fry** [gazay/gon#5]
Exception raised:
undefined local variable or method `include_gon' for #ActionView::Base:0xbac8298

rails 2.3.11, ruby 1.8.7 (2011-02-18 patchlevel 334) [i686-linux], MBARI 0x8770, Ruby Enterprise Edition 2011.03

Works fine after manual adding helper code to application_helper.rb:

```
def include_gon
  data = Rails.cache.read('gon_variables') || {}

  script = "<script>window.Gon = {};"
  data.each do |key, val|
    script += "Gon." + key.to_s + val.to_json + ";"
  end
  script += "</script>"
  script.html_safe
end
```

**Comment by gokulakrishna19** [comment]
will it work for rails 5
