### ISSUE TITLE
NameError (undefined local variable or method `gon')

### ISSUE THREAD

**Issue by ggrillone** [gazay/gon#55]
So I'm receiving this message with gone: NameError (undefined local variable or method `gon').  When running this on my local machine everything works great.  However, when I try to access the app on my production server I receive the above error.  Is there any kind of special configuration for gon that needs to be done for the production server? I checked that gon was in my Gemfile.lock file (it is) and I ran gem install gon anyways just to be safe, but I'm still getting the error.
Any ideas?

**Comment by Evanto** [comment]
I'm also having this error locally in development. Restarting the server doesn't help. The gon gem behaves strangely: if I install it via `gem install gon` + `bundle install`, the console says it was installed, but if I check the Gemfile, there is no gon there. When I install it via adding to the Gemfile, the console signals ok but gon is absent in the gemfile.lock and throws the NameError as well.

**Comment by motoakim** [comment]
It seems that I got the same error as @Evanto
