### ISSUE TITLE
Update gon variables on an ajax request

### ISSUE THREAD

**Issue by benniemietz** [gazay/gon#56]
Is there any way to update the complete gon variable in the DOM on an ajax request? I want to update all of my gon variables when making my request.

**Comment by ULKARAMAKRISHNAN** [comment]
Hi,

I do gon.variable_name = value in my controller and in my js file I use gon.variable_name. It works fine for full page reloads but for ajax request it doesnt gets updated. 

Say for example on page reload, in my controller I do gon.variable_name = value1 and in my js gon.variable_name gives me value1. After a ajax request in my controller I do gon.variable_name = value2 and in my js I strill see gon.variable_name as value1 only.

Is there any way I could update gon.variable_name in a ajax request?

Thanks
