### ISSUE TITLE
watch.js does not integrate with the rails pipeline

### ISSUE THREAD

**Issue by bigtunacan** [gazay/gon#87]
The current setup of the gon gem is such that the watch.js file does not integrate with the Rails 3 asset pipeline.

I have been using the konacha javascript testing gem

https://github.com/jfirebaugh/konacha?source=c

When I try to require watch.js in a mocha spec file as
```
    //= require watch
```
the file will fail to load due to not finding watch.js in the asset pipeline.

**Comment by gazay** [comment]
Let me close this inactive issue
