### ISSUE TITLE
gon/wiki/Installation contains outdated information

### ISSUE THREAD

**Issue by hak8or** [gazay/gon#92]
I haven't got the faintest clue if I am posting this in the correct place, so apologies if I am.

The installation page does not include an item for Rails 4.0.0 so I used the item for Rails v3 which says to include gon v3.0.5. This created the blankslate issue similar to this: http://www.nigelthorne.com/2010/03/ruby-blankslate-issue-or-problem-with.html

Using the most recent version of gon fixes this issue.

My suggestion is to update the installation page to include an item for rails V4 in an effort to avoid this possible confusion for others in the future.

**Comment by takiy33** [comment]
I close this issue because README.md and gon/wiki/Installation are updated.
If you have question or problem, please feel free to reopen it.
